name: GitHub Action
description: Outputs a capitalized string of whatever the input string is.
outputs:
  increment:
    description: Either 'major', 'minor', 'patch', or 'none'.
    value: ${{ steps.main.outputs.increment }}
runs:
  using: composite
  steps:
    - run: pnpm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: pnpm build
      shell: bash
      working-directory: ${{ github.action_path }}
    - id: main
      run: pnpm start
      shell: bash
      working-directory: ${{ github.action_path }}